### ISSUE TITLE
Assigning colors in 6 lane mode not working correctly

### ISSUE THREAD

**Issue by tomhon** [DaveVoyles/React-Native-Ski-Team#31]
'Color 1', 'Color 2' showing up on screen
![20180116_204529000_ios](https://user-images.githubusercontent.com/10427474/35011538-58f0a0bc-fabb-11e7-8ad0-d81cc77d56b6.png)

**Comment by roblesch** [comment]
The smaller labels are a feature of the modal dropdown package being used for color selection - fix would be to use another package (requires code refactor) or change the package (fork package, make change, upload to npm)
